/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frm_Servidor.java
 *
 * Created on 14/10/2015, 13:02:51
 */
package ep1_redes;

import javax.swing.JOptionPane;

/**
 *
 * @author Elton
 */
public class frm_Servidor extends javax.swing.JFrame {

    Servidor server = new Servidor(this);

    /** Creates new form frm_Servidor */
    public frm_Servidor() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        strPortaInciarServidor = new javax.swing.JTextField();
        btnIniciarServidor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Servidor");

        btnIniciarServidor.setText("Iniciar");
        btnIniciarServidor.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarServidorActionPerformed(evt);
            }
        });

        //strTextosLogsServidor.setColumns(20);
        //strTextosLogsServidor.setRows(5);
        //jScrollPane1.setViewportView(strTextosLogsServidor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(184, 184, 184).addComponent(jLabel1)).addGroup(layout.createSequentialGroup().addGap(22, 22, 22).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE).addGroup(layout.createSequentialGroup().addComponent(strPortaInciarServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(18, 18, 18).addComponent(btnIniciarServidor))))).addContainerGap(33, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(21, 21, 21).addComponent(jLabel1).addGap(42, 42, 42).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(strPortaInciarServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(btnIniciarServidor)).addGap(34, 34, 34).addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(23, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarServidorActionPerformed
        Integer portaListener = Integer.parseInt(strPortaInciarServidor.getText());
        if (portaListener > 0) {
            try {
                    server.porta = portaListener;
                    server.novasConexoes();
                    //System.err.println("caiu conexao");
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            JOptionPane.showMessageDialog(null, "Conectado ao servidor com sucesso!", "CONECTADO", JOptionPane.INFORMATION_MESSAGE);                            
                        }
                    });                                        
            } catch (Exception e) {
                System.err.println("Erro: " + e.getMessage());
                this.dispose(); 
            }
        }

        btnIniciarServidor.setEnabled(false);
        strPortaInciarServidor.setEnabled(false);
    }//GEN-LAST:event_btnIniciarServidorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Servidor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarServidor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField strPortaInciarServidor;
    //private javax.swing.JTextArea strTextosLogsServidor;
    // End of variables declaration//GEN-END:variables
}
