/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmAlertaStatus.java
 *
 * Created on 20/10/2015, 13:11:36
 */
package ep1_redes;

import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;
import java.awt.event.WindowEvent;

/**
 *
 * @author Elton
 */
public class frmAlertaStatus extends javax.swing.JFrame {

    /** Creates new form frmAlertaStatus */
    public frmAlertaStatus(String userName, String status) throws InterruptedException {        
        initComponents();        
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice defaultScreen = ge.getDefaultScreenDevice();
        Rectangle rect = defaultScreen.getDefaultConfiguration().getBounds();
        int x = (int) rect.getMaxX() - this.getWidth();
        int y = (int) rect.getMaxY() - this.getHeight();
        this.setLocation(x, y);
        lblNomeUsuario.setText(userName);
        lblStatus.setText(status);               
    }
    
    public void sleepAndDie(){
        try {
            Thread.sleep(5000); 
            this.dispose(); 
        } catch (Exception e) {
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeUsuario = new javax.swing.JLabel();
        lblLegendaEsta = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Status"); // NOI18N

        lblNomeUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNomeUsuario.setText("UserName");

        lblLegendaEsta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLegendaEsta.setText("Está: ");

        lblStatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblStatus.setText("Status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeUsuario)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLegendaEsta)
                        .addGap(41, 41, 41)
                        .addComponent(lblStatus)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblNomeUsuario)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLegendaEsta)
                    .addComponent(lblStatus))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {               
       Runnable r = new Runnable() {
            public void run() {
                try {
                    frmAlertaStatus frm;
                    frm = new frmAlertaStatus("Elton", "Online");
                    frm.setVisible(true);
                    frm.sleepAndDie();
                } catch (Exception e) {
                    System.err.println("Erro ao abrir janela de status: " + e.toString());
                }
            }
        };
        new Thread(r).start();        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLegendaEsta;
    private javax.swing.JLabel lblNomeUsuario;
    private javax.swing.JLabel lblStatus;
    // End of variables declaration//GEN-END:variables
}
